// Code generated by sqlc. DO NOT EDIT.

package usersdb

import (
	"time"
)

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
